### ISSUE TITLE
Potential minor issue when building the fonts

### ISSUE THREAD

**Issue by ggnkua** [dciabrin/ngdevkit-examples#11]
Hello,

For various reasons I was looking over the build system of the examples, when I noticed the following snippet

https://github.com/dciabrin/ngdevkit-examples/blob/df3c5ab677ea3aa03e3166e58a20c7b4bce1bdf6/assets/Makefile#L33-L37

In line 37, is it deliberate to use `talltext.png` instead of (what I assume should be right) `talltext-shadow.png`? At least as-is line 37 isn't consistent with line 34.

Thanks for your time and looking forward to your reply,
George

**Comment by dciabrin** [comment]
> In line 37, is it deliberate to use `talltext.png` instead of (what I assume should be right) `talltext-shadow.png`? At least as-is line 37 isn't consistent with line 34.

Yes it is, this produces two different sets of base fixed-tiles ROMs. Each base ROM contains respectively flat text and shadowed text, but they all share the same base characters for option -b, which is used during the eye-catcher sequence implemented in the original neo geo BIOS.

This text is not used by the opensource BIOS replacement provided by ngdevkit (nullbios), as it currently doesn't provide any eye catcher :)

**Comment by ggnkua** [comment]
Oh okay, makes sense. Thanks!

And also thank you for your work on the SDK!
