### ISSUE TITLE
Sprite rendering order

### ISSUE THREAD

**Issue by tatsunootoshigo** [dciabrin/ngdevkit-examples#3]
Hi,
The order the sprites are rendered should be dependent to the drawing order but loos like the sprite rendering order is determined by the order in the CROMs.
For example, if I change the order I draw sprites in the main loop, then nothing change on screen. On the contrary, if I change the order they are stored in the CROMs (and set sprite/tile offset accordingly) then the rendering order is affected.
Thank you for your help

**Comment by tatsunootoshigo** [comment]
Hi,
The order the sprites are rendered should be dependent to the drawing order but loos like the sprite rendering order is determined by the order in the CROMs.
For example, if I change the order I draw sprites in the main loop, then nothing change on screen. On the contrary, if I change the order they are stored in the CROMs (and set sprite/tile offset accordingly) then the rendering order is affected.
Thank you for your help

**Comment by dciabrin** [comment]
The hardware doesn't really _draw_ sprite image into some kind of frame buffer unlike e.g. what is done in computer graphics, so in fact the rendered image doesn't depend on the drawing order.

Rather, the rendering of sprites is done by the "sprite controller" chip. This chip has a fixed rendering pipeline which draws the sprites on screen based on their order in the VRAM: the higher sprite numbers are rendered on top of the lower ones.

**Comment by tatsunootoshigo** [comment]
Thank you for your reply.
I understand better now. I thought there was some kind of framebuffer actually.
So to draw a sprite in front of another one, I simply have to set the sprite offset accordingly correct?

**Comment by dciabrin** [comment]
> So to draw a sprite in front of another one, I simply have to set the sprite offset accordingly correct?

That's correct

**Comment by tatsunootoshigo** [comment]
Sorry I didn't close earlier.
