### ISSUE TITLE
Name of the game in softdips menu

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit-examples#9]
Hi

I had very good results with the softdips configurations, well inspired by the example 08.

Now the problem is my game shows as "ngdevkit ROM" in the softdips menu.

Is it possible to change this name ?

**Comment by dciabrin** [comment]
If you're using soft-dip.h, check whether you're generating DIP settings for all languages, as shown in example 08.
By default, when the linker doesn't see a config in your object file, it tries to import a default from ngdevkit for each language.

In example 08, you shouldn't see such default in the ROM file.

**Comment by totologic** [comment]
Yes it works. Actually the problem came from the MAME I use. He kept old names in some old SAVERAM files. After deleting these files, I can see the game is properly updated with the GENERATE_DIP macro.
